# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually
_commit: v2.2.4
_src_path: gh:FallingColors/hexdummy
advanced: false
description: MieHex:Revolution addon for Hex Casting,as an addtion for miehex.
display_name: MieHex:Revolution
github_repo: MieHex:Revolution
github_user: xm1221
java_package: cn.xm1221.MieHexRevolution
mappings_name: Mojmap
minecraft_version_in_mod_version: false
mit_license: true
mod_version: 0.0.1
modid: miehex_revolution
