# non-minecraft values
org.gradle.jvmargs=-Xmx4096M
jetbrainsAnnotationsVersion=23.0.0

# gradle kotlin jvm plugin breaks without this
kotlin.stdlib.default.dependency=false

# mod info
mavenGroup=cn.xm1221.MieHexRevolution
modId=miehex_revolution
modVersion=1.0.3.1


# publishing (TODO: fill these in!)
curseforgeId=
modrinthId=xm1221
